--------------------------------------------------------
--  파일이 생성됨 - 화요일-8월-25-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "C##EZEN"."ORDERS" 
   (	"ORDERID" NUMBER, 
	"MENU" VARCHAR2(1000 BYTE), 
	"PRICE" NUMBER, 
	"DELIVERYFLAG" NUMBER, 
	"DELIVERYFEE" NUMBER, 
	"BRANDID" NUMBER, 
	"USERID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##EZEN.ORDERS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007512
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EZEN"."SYS_C007512" ON "C##EZEN"."ORDERS" ("ORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "C##EZEN"."ORDERS" MODIFY ("MENU" NOT NULL ENABLE);
  ALTER TABLE "C##EZEN"."ORDERS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##EZEN"."ORDERS" ADD PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "C##EZEN"."ORDERS" ADD CONSTRAINT "FK_USERID" FOREIGN KEY ("USERID")
	  REFERENCES "C##EZEN"."MEMBER" ("USERID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##EZEN"."ORDERS" ADD CONSTRAINT "FK_BRANDID" FOREIGN KEY ("BRANDID")
	  REFERENCES "C##EZEN"."BRAND" ("BRANDID") ON DELETE CASCADE ENABLE;
